// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOYzeGSpAiMqqdIsshAAj3TvFCcD7gyQ',
    appId: '1:795326767573:web:8ea07e381a41d331949d5c',
    messagingSenderId: '795326767573',
    projectId: 'firebase-quiz-project',
    authDomain: 'fir-quiz-project-d04f4.firebaseapp.com',
    storageBucket: 'firebase-quiz-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-eAY3YjWn2rhaDDP6SsagRlsDCyG4iOc',
    appId: '1:795326767573:android:4f2520d1e806121f949d5c',
    messagingSenderId: '795326767573',
    projectId: 'firebase-quiz-project',
    storageBucket: 'firebase-quiz-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtXtoEfG_JA6I0kxKm63dVZkreBWY8fmE',
    appId: '1:795326767573:ios:156cc4278b10f58c949d5c',
    messagingSenderId: '795326767573',
    projectId: 'firebase-quiz-project',
    storageBucket: 'firebase-quiz-project.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtXtoEfG_JA6I0kxKm63dVZkreBWY8fmE',
    appId: '1:795326767573:ios:156cc4278b10f58c949d5c',
    messagingSenderId: '795326767573',
    projectId: 'firebase-quiz-project',
    storageBucket: 'firebase-quiz-project.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmOYzeGSpAiMqqdIsshAAj3TvFCcD7gyQ',
    appId: '1:795326767573:web:4df36c84ba821399949d5c',
    messagingSenderId: '795326767573',
    projectId: 'firebase-quiz-project',
    authDomain: 'fir-quiz-project-d04f4.firebaseapp.com',
    storageBucket: 'firebase-quiz-project.firebasestorage.app',
  );

}